monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = true
        # Prevents apps from changing hardware mixer tracks directly
        api.alsa.ignore-dB = true
      }
    }
  }
]
