# Background and foreground colors
background = #060E00
foreground = #EFF000

# Standard colors
palette = 0=#060E00
palette = 1=#a79652
palette = 2=#b4cf7e
palette = 3=#ecfd95
palette = 4=#489267
palette = 5=#d4a34b
palette = 6=#acf094
palette = 7=#EFF000

# Bright colors
palette = 8=#61645e
palette = 9=#c1ab54
palette = 10=#c7e97d
palette = 11=#ebff79
palette = 12=#4dab76
palette = 13=#f5b63b
palette = 14=#b7ff98
palette = 15=#f4f7ec
