$color = rgba(6, 14, 0, 1)
$inner_color = rgba(6, 14, 0, 0.66)
$outer_color = rgba(212, 163, 75, 1)
$font_color = rgba(239, 240, 0, 1)
$placeholder_color = rgba(239, 240, 0, 0.7)
$check_color = rgba(172, 240, 148, 1)
