background            #060E00
foreground            #EFF000

# black
color0  #060E00
color8  #61645e

# red
color1  #a79652
color9  #c1ab54

# green
color2  #b4cf7e
color10 #c7e97d

# yellow
color3  #ecfd95
color11 #ebff79

# blue
color4  #489267
color12 #4dab76

# magenta
color5  #d4a34b
color13 #f5b63b

#cyan
color6  #acf094
color14 #b7ff98

#white
color7  #EFF000
color15 #f4f7ec


