context.modules = [
{   name = libpipewire-module-loopback
    args = {
        node.description = "VAIO Hearing In"
        capture.props = {
            node.name = "VAIO Hearing In"
            media.class = Audio/Sink
        },
        playback.props = {
            node.name = "VAIO Hearing In"
            media.class = Audio/Source
        }
    }
},
{   name = libpipewire-module-loopback
    args = {
        node.description = "VAIO Desktop Mic - Spotify"
        capture.props = {
            node.name = "VAIO Desktop Mic - Spotify"
            media.class = Audio/Sink
        },
        playback.props = {
            node.name = "VAIO Desktop Mic - Spotify"
            media.class = Audio/Source
        }
    }
},
{   name = libpipewire-module-loopback
    args = {
        node.description = "VAIO Desktop Mic Setup"
        capture.props = {
            node.name = "VAIO Desktop Mic Setup"
            media.class = Audio/Sink
        },
        playback.props = {
            node.name = "VAIO Desktop Mic Setup"
            media.class = Audio/Source
        }
    }
},
{   name = libpipewire-module-loopback
    args = {
        node.description = "VAIO Game Sound"
        capture.props = {
            node.name = "VAIO Game Sound"
            media.class = Audio/Sink
        },
        playback.props = {
            node.name = "VAIO Game Sound"
            media.class = Audio/Source
        }
    }
}
]