-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- =====================================================================

-- 1. WAYLAND CORE & DISPLAY ENVS (Organized & Modernized)

-- =====================================================================

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

-- =====================================================================

-- 2. NVIDIA HARDWARE ACCELERATION

-- =====================================================================

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("VK_DRIVER_FILES", "/usr/share/vulkan/icd.d/nvidia_icd.json")

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

-- Often required for NVIDIA cursors

-- =====================================================================

-- 3. STEAMVR / INDEX SPECIFIC CONFIGS

-- =====================================================================

hl.env("STEAMVR_USE_XWAYLAND", 1)

hl.env("STEAMVR_FORCE_XWAYLAND", 1)

hl.env("STEAMVR_DIRECT_MODE", 1)

hl.env("AQUAMARINE_DRM_LEASE", 1)

hl.env("__GL_GSYNC_ALLOWED", 0)

hl.env("__GL_SYNC_TO_VBLANK", 0)

-- =====================================================================

-- 4. COMPATIBILITY TOGGLES (Commented out by default unless needed)

-- =====================================================================

hl.env("SDL_AUDIODRIVER", "pulseaudio")

-- env = WLR_DRM_NO_ATOMIC,1

--env = XDG_TEMPLATES_DIR,$HOME/.config/nautilus/Templates
