windowrule = workspace 6, match:title ^(gamescope)$
windowrule = workspace 6, match:title ^(Deadlock)$
windowrule = workspace 6, match:title ^(Terraria)$
workspace = 6, monitor:DP-1
windowrule = match:title ^(Steam)$,workspace 1, tile on, group set new always
